// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrjgvtwtywsgjydzkbdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhyamd2dHd0eXdzZ2p5ZHprYmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzkyMDAsImV4cCI6MjA2MzA1NTIwMH0.8_Gs0tJRGS2v5uHzzihciO2QAnMFYDOASxxdwna6aLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);